apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: etcd-infra
  name: etcd-backup-scripts
  namespace: etcd-infra
data:
  manage-backup: |-
    #!/usr/bin/bash -x
    echo "beginning backup process to $BACKUP_PATH"
    cd /tmp
    mkdir -p $BACKUP_PATH
    export DATESTRING=$(date "+%F_%H%M%S")
    echo entering host  
    chroot /host /usr/local/bin/cluster-backup.sh /home/core/assets/backup 
    ls -d -1tr ${BACKUP_PATH}/*  | head -n -4 | xargs -d '\n' rm -rf
    mkdir -p ${BACKUP_PATH}/${DATESTRING}
    cd ${DATESTRING}
    cp -r /host/home/core/assets/backup/ .
    rm -rf /host/home/core/assets/backup
    exit $?
