kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup
  namespace: etcd-infra
  labels:
    app: etcd-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: etcd-backup-data
  storageClassName: gp2
  volumeMode: Filesystem